version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
    container_name: node-express-nginx  
    ports:
      - 8081:80
    networks:
      - node-express

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    container_name: node-express-app
    restart: unless-stopped
    environment:
      - PORT=3001
      - LOCATION=DHAKA
    ports:
      - 3001:3001
    networks:
      - node-express  
    command: npm run start

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    container_name: node-express-web
    restart: unless-stopped
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - LOCATION=CUMILLA
    networks:
      - node-express  
    command: npm run start  

networks:
  node-express:
    driver: bridge